#!/usr/bin/env sh
set -eu

commit_msg_file="${1:-}"

if [ -z "$commit_msg_file" ] || [ ! -f "$commit_msg_file" ]; then
  echo "Commit validation failed: commit message file not found."
  exit 1
fi

commit_msg="$(head -n 1 "$commit_msg_file")"

# Allow merge/revert commits generated by Git.
if printf '%s' "$commit_msg" | grep -Eq '^(Merge|Revert )'; then
  exit 0
fi

pattern='^(feat|style|fix|refactor|chore)(\([a-z0-9._/-]+\))?(!)?: .+'

if ! printf '%s' "$commit_msg" | grep -Eq "$pattern"; then
  echo "Invalid commit message format."
  echo "Use Conventional Commits, for example:"
  echo "  feat(auth): add login mutation"
  echo "  style(header): reorder responsive classes"
  echo "  fix(users): handle empty response"
  echo "  refactor(api): simplify env access"
  echo "  chore: update lint rules"
  exit 1
fi
